// <auto-generated />
namespace MessageStack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PrivateMessageChatId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrivateMessageChatId));
        
        string IMigrationMetadata.Id
        {
            get { return "202001302050121_PrivateMessageChatId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
